apiVersion: v1
kind: ConfigMap
metadata:
  name: levantamento-mongo-env
data:
  DATABASE_URL: "mongodb+srv://user:user@levantamentopatrimonial.yqdhjoo.mongodb.net/"
  PORT: "3000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-levantamento
spec:
  selector:
    matchLabels:
      app: api-levantamento
  template:
    metadata:
      labels:
        app: api-levantamento
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: api-levantamento
        image: registry.fslab.dev/pablosmolak/api-levantamento:latest
        envFrom:
        - configMapRef:
            name: levantamento-mongo-env
        resources: {}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-levantamento
spec:
  type: ClusterIP
  selector:
    app: api-levantamento
  ports:
  - port: 80
    targetPort: 3000

